# Generated by Django 6.1 on 2026-08-14 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('company', models.CharField(blank=True, default='', max_length=150)),
                ('job_title', models.CharField(blank=True, default='', max_length=150)),
                ('category', models.CharField(choices=[('Personal', 'Personal'), ('Work', 'Work'), ('Family', 'Family'), ('Client', 'Client'), ('Friend', 'Friend'), ('Other', 'Other')], default='Personal', max_length=50)),
                ('is_favorite', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('avatar_color', models.CharField(blank=True, default='indigo', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_favorite', 'name'],
            },
        ),
    ]
